### ISSUE TITLE
Alternate CS pin on ESP32

### ISSUE THREAD

**Issue by gcormier** [ZinggJM/GxEPD2#12]
I'm curious why CS can't be moved to a different pin. It is a simple low/high toggle to enable the chip.

With the default setup, my 4.2" display demo works fine on an ESP32.

`GxEPD2_BW<GxEPD2_420, GxEPD2_420::HEIGHT> display(GxEPD2_420(5,17,16,4));`

However, if I change the CS pin to GPIO19, the display stops working.

`GxEPD2_BW<GxEPD2_420, GxEPD2_420::HEIGHT> display(GxEPD2_420(19,17,16,4));`

Since it is a simple toggle, should it not work on the new pin?

**Comment by ZinggJM** [comment]
Why do you think this is an issue with the library? Did you read the issue_template.md?

The Arduino Forum Displays is the appropriate place to ask such questions!

Don't forget to specify the ESP32 variant you are asking for; there are several main variants, and many different processor boards and compile variants in the package for the Arduino IDE.

You could also consult the processor manual of your ESP32 from espressif.com.
