### ISSUE TITLE
ATTINY85, or other chip pinout

### ISSUE THREAD

**Issue by Mrkisha** [ZinggJM/GxEPD2#16]
I've used this library for e-paper and wemos D1.

How can I use it with attiny85, or some other chip (nrf52)?

**Comment by ZinggJM** [comment]
Thank you for your interest in GxEPD2.
But please note that I do not like questions being asked in the form of issues.
**Please use the Arduino Forum Displays** for asking questions or suggesting enhancements.

You locate the file `pins_arduino.h` for your target system, to find the pins used for HW SPI.
You select suitable general IO pins for CS, DC, RST and BUSY.
You create a constructor for your e-paper display with the parameters set for your selection.
You select the template parameter for HEIGHT such that the display buffer fits in your targets RAM.
The example for AVR shows how this can be easily achieved for small ram targets:
```
#define MAX_DISPAY_BUFFER_SIZE 800 // 
#define MAX_HEIGHT(EPD) (EPD::HEIGHT <= MAX_DISPAY_BUFFER_SIZE / (EPD::WIDTH / 8) ? EPD::HEIGHT : MAX_DISPAY_BUFFER_SIZE / (EPD::WIDTH / 8))
// select one and adapt to your mapping
//GxEPD2_BW<GxEPD2_154, MAX_HEIGHT(GxEPD2_154)> display(GxEPD2_154(/*CS=10*/ SS, /*DC=*/ 8, /*RST=*/ 9, /*BUSY=*/ 7));
```
