### ISSUE TITLE
Duplicated assignment?

### ISSUE THREAD

**Issue by gnietof** [ZinggJM/GxEPD2#6]
I have found an assignment in line 101 of GxEPD2_3C.h which IMHO is duplicated. Otherwise, why is this assigned twice?

_color_buffer[i] = _color_buffer[i] = (_color_buffer[i] | (1 << (7 - x % 8)));

https://github.com/ZinggJM/GxEPD2/blob/3e35c0c4974fae896f583de04a2d43b9ec5bf349/src/GxEPD2_3C.h#L101

**Comment by ZinggJM** [comment]
And where is the issue? It doesn't hurt, except your and my eyes.

Thank you for reporting anyway.

**Comment by ZinggJM** [comment]
Fixed in Version 1.1.2
