### ISSUE TITLE
Add Teensy Support

### ISSUE THREAD

**Issue by imaluschi** [ZinggJM/GxEPD2#9]
### Expected Behavior
Teensy Supported
### Actual Behavior
No support for Teensy
### E-Paper module used
Waveshare 1.54", GDEW0154Z04
### Arduino / Processor module used
Teensy 3.5

It's actually working in my case, I had to remove the `#if defined` and keep only one line:
`GxEPD2_3C<GxEPD2_154c, GxEPD2_154c::HEIGHT> display(GxEPD2_154c(/*CS=*/ 10, /*DC=*/ 7, /*RST=*/ 9, /*BUSY=*/ 8));`

As mentioned, Waveshare 1.54" (3 Color) on Teensy 3.5, connection according to the code above.
Maybe you can add it at least on your 32bit version.

Anyway, good work - Thanks!!

**Comment by ZinggJM** [comment]
@imaluschi,

So you have an issue with this library, although obviously you were able to use your e-paper display on your Teensy 3.5 with this library?

You can donate a Teensy 3.5 to me, then I will add example support for it to boards_added.h.
Or you can donate the whole family of Teensy boards to me, then I will add teensy_boards_added.h to the example.

Ok, this answer took me just 5 minutes of my time. Cheers.
